# Generated by Django 3.0.3 on 2020-09-15 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='topic_notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.Topic'),
        ),
    ]
